import { ArrowLeft, CircleAlert, ShieldCheck } from "lucide-react";

const sections = [
  ["Software access and scope", "FizuxCoder provides access to the EA packages and related portal workflow described on this website, subject to verified payment, active entitlement, and any stated product-specific terms. A paid receipt does not create access until the receipt is successfully verified against the matching portal account. Package files are available only through the protected portal library for an active entitlement."],
  ["Licence binding and account security", "An active customer may bind the numeric MT5 account that will run the licensed EA. A later re-binding replaces the prior account. You are responsible for securing your portal login, MT5 credentials, broker account, devices, and downloaded package files. Do not share a settlement reference, protected package, or account access with another person."],
  ["Automated service e-mails", "After a verified production receipt claim, FizuxCoder may send an activation or installation notice to the e-mail address of the authenticated portal account. These messages are service notices, not trading signals, financial advice, or a guarantee of delivery. If an e-mail is delayed or unavailable, the portal remains the source for entitlement status, binding, and protected downloads."],
  ["Risk and customer responsibility", "Expert Advisors are software tools used in a trading environment. Automated trading carries risk, including loss from market volatility, gaps, liquidity conditions, spreads, slippage, connectivity problems, broker execution, configuration error, or software failure. Nothing on this site is investment, legal, or tax advice, and no result, profitability, or suitability is promised. Test in a demo environment and obtain independent advice where appropriate."],
  ["Payments, third parties, and updates", "ToyyibPay operates payment processing, and the optional Pepperstone registration link is disclosed separately as a referral link. Third-party services are governed by their own terms. EA updates are made available through the active product library when released; customers should follow the applicable setup and update guidance before replacing a running EA or component."],
  ["Contact and changes", "Questions about these terms, a verified purchase, or portal access may be sent to xtr0zen@gmail.com. These terms and the portal workflow may be updated to reflect operational, legal, or security changes. The current version is available on this public page."],
] as const;

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#f4f0e8] text-[#17201f]">
      <header className="border-b border-[#17201f]/10 bg-[#f4f0e8]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-18 max-w-[1100px] items-center justify-between px-5 lg:px-10"><a href="/" className="inline-flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#0e716e]"><ArrowLeft size={15} /> Back to briefing</a><a href="/portal" className="button-primary button-small">Customer portal</a></div></header>
      <main className="px-5 py-14 lg:px-10 lg:py-20"><article className="mx-auto max-w-[920px]"><p className="font-mono text-[10px] font-bold uppercase tracking-[.15em] text-[#0e716e]">FizuxCoder / customer service terms</p><h1 className="mt-5 max-w-3xl font-display text-[clamp(3.4rem,7vw,6.3rem)] leading-[.88] tracking-[-.065em]">Access has boundaries. <em className="font-normal text-[#0e716e]">Read them first.</em></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#52605d]">Effective 19 August 2026. These terms describe the customer portal, verified purchase claims, licence binding, protected package delivery, and service e-mail notices.</p><div className="mt-10 flex flex-col gap-4 rounded-[1.5rem] border border-[#e5a631]/55 bg-[#fff5d8] p-6 sm:flex-row"><CircleAlert className="shrink-0 text-[#b6780b]" size={25} /><p className="text-sm leading-6 text-[#5a461e]"><strong>Risk notice.</strong> Automated trading can result in substantial losses. Review software settings and broker conditions independently, use a demo environment first, and do not treat any automation feature as a promise of trading performance.</p></div><div className="mt-12 space-y-8">{sections.map(([title, body], index) => <section key={title} className="border-t border-[#17201f]/15 pt-7"><p className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#e5a631]">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-3 font-display text-3xl tracking-[-.04em]">{title}</h2><p className="mt-4 max-w-3xl text-[.98rem] leading-7 text-[#52605d]">{body}</p></section>)}</div><div className="mt-12 rounded-[1.5rem] bg-[#17201f] p-6 text-[#f4f0e8]"><ShieldCheck className="text-[#e5a631]" size={26} /><p className="mt-4 text-sm leading-6 text-[#c7d1cb]">The protected portal is the authoritative record for active entitlement, MT5 binding, and current package availability.</p></div></article></main>
    </div>
  );
}
