export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  ownerEmail: process.env.OWNER_EMAIL ?? "xtr0zen@gmail.com",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  gmailOauthClientId: process.env.GMAIL_OAUTH_CLIENT_ID ?? "",
  gmailOauthClientSecret: process.env.GMAIL_OAUTH_CLIENT_SECRET ?? "",
  gmailSenderEmail: process.env.GMAIL_SENDER_EMAIL ?? "",
  threadsAppId: process.env.THREADS_APP_ID ?? "",
  threadsAppSecret: process.env.THREADS_APP_SECRET ?? "",
  masterServerSyncKey: process.env.MASTER_SERVER_SYNC_KEY ?? "",
  geminiEventIngestKey: process.env.GEMINI_EVENT_INGEST_KEY ?? "",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  telegramMarketingInviteLink: process.env.TELEGRAM_MARKETING_INVITE_LINK ?? "",
};
